### ISSUE TITLE
Redo the merge

### ISSUE THREAD

**Issue by ramonaZmole** [Mexaby/EvozonInternship#5]
You did the merge from the merge branch into the main branch.

Create merge2 branch from this point 
![image](https://github.com/Mexaby/EvozonInternship/assets/12456781/66b04a9d-3444-4dbd-835a-a8ad4a95eab4)

Add a new file and push the changes 
Merge the main branch into the merge2 branch

**Comment by Mexaby** [comment]
Done, I think.
